drop extension if exists "pg_net";

create type "public"."custom_roles" as enum ('rider', 'client');

create type "public"."delivery_status" as enum ('pending', 'arriving_pickup', 'in_transit', 'delivered');


  create table "public"."__diesel_schema_migrations" (
    "version" character varying(50) not null,
    "run_on" timestamp without time zone not null default CURRENT_TIMESTAMP
      );



  create table "public"."app_custom_users" (
    "id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "username" text not null,
    "custom_role" public.custom_roles not null default 'client'::public.custom_roles,
    "phone" bigint,
    "profileImage" text
      );


alter table "public"."app_custom_users" enable row level security;


  create table "public"."app_delivery_orders" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "client_id" uuid not null default auth.uid(),
    "image_url" text,
    "pickup_lat" numeric,
    "pickup_long" numeric,
    "dropoff_lat" numeric,
    "dropoff_long" numeric,
    "driver_initial_lat" numeric,
    "driver_initial_long" numeric,
    "status" public.delivery_status not null default 'pending'::public.delivery_status,
    "order_code" text not null default 'asap'::text,
    "driver_id" uuid,
    "modified_at" timestamp with time zone not null default now(),
    "pickup_name" text,
    "dropoff_name" text,
    "dropoff_code" text,
    "pickup_code" text,
    "is_dropoff_code_authenticated" boolean not null default false,
    "is_pickup_code_authenticated" boolean not null default false,
    "pickup_time" timestamp with time zone,
    "dropoff_time" timestamp with time zone,
    "delivery_accepted_time" timestamp with time zone,
    "package_description" text,
    "package_type" text,
    "initial_waypoints" jsonb
      );


alter table "public"."app_delivery_orders" enable row level security;


  create table "public"."app_delivery_orders_waypoints" (
    "order_id" bigint generated by default as identity not null,
    "lat" numeric,
    "long" numeric,
    "created_at" timestamp with time zone not null,
    "id" bigint generated by default as identity not null
      );


alter table "public"."app_delivery_orders_waypoints" enable row level security;


  create table "public"."app_locations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "longitude" numeric not null,
    "latitude" numeric not null,
    "frontend_order_id" uuid not null
      );


alter table "public"."app_locations" enable row level security;


  create table "public"."app_messages" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "sender_id" uuid not null default gen_random_uuid(),
    "receiver_id" uuid not null default gen_random_uuid(),
    "delivery_order_id" bigint not null,
    "message" text not null default 'ss'::text,
    "is_read" boolean not null default false
      );


alter table "public"."app_messages" enable row level security;


  create table "public"."app_package_images" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "url" text not null,
    "user_id" uuid not null default auth.uid()
      );


alter table "public"."app_package_images" enable row level security;


  create table "public"."app_riders_current_status" (
    "id" uuid not null,
    "updated_at" timestamp with time zone not null default now(),
    "email" character varying not null,
    "longitude" numeric not null,
    "latitude" numeric not null,
    "active_mode" public.custom_roles not null default 'client'::public.custom_roles
      );


alter table "public"."app_riders_current_status" enable row level security;


  create table "public"."app_saved_locations" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "latitude" numeric,
    "longitude" numeric,
    "user_id" uuid default auth.uid()
      );


alter table "public"."app_saved_locations" enable row level security;


  create table "public"."app_settings" (
    "id" uuid not null,
    "delivery_alerts" boolean,
    "promotions" boolean,
    "sms_updates" boolean
      );


alter table "public"."app_settings" enable row level security;


  create table "public"."azzz----------BACKEND DB-------" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."azzz----------BACKEND DB-------" enable row level security;


  create table "public"."back__diesel_schema_migrations" (
    "version" character varying(50) not null,
    "run_on" timestamp without time zone not null default CURRENT_TIMESTAMP
      );



  create table "public"."back_custom_users" (
    "rider_id" uuid not null,
    "rider_pubkey" jsonb not null,
    "name" text not null,
    "email" text not null,
    "phone" text not null
      );



  create table "public"."back_drivers" (
    "driver_id" uuid not null,
    "driver_pubkey" jsonb not null,
    "name" text not null,
    "email" text not null,
    "phone" text not null,
    "status" text not null,
    "driver_location" jsonb not null,
    "license_number" text,
    "vehicle_type" text not null,
    "driver_response" jsonb not null,
    "vehicle" text
      );



  create table "public"."back_ride_request" (
    "request_id" uuid not null,
    "rider_id" uuid,
    "pick_up" jsonb not null,
    "drop_off" jsonb not null,
    "estimated_price" bigint not null,
    "distance_km" double precision not null,
    "estimated_time_min" integer not null,
    "ride_type" jsonb not null,
    "items" jsonb not null,
    "payment_method" text not null,
    "order_id" uuid,
    "user_id" bigint,
    "user_phone_number" text,
    "vendor_phone_number" text
      );



  create table "public"."back_trips" (
    "trip_id" bytea not null,
    "rider_id" uuid not null,
    "reference" text not null,
    "pickup_points" jsonb not null,
    "dropoff_points" jsonb not null,
    "driver_initial_points" jsonb not null,
    "rider_pubkey" text not null,
    "driver_pubkey" text not null,
    "driver_id" uuid not null,
    "status" text not null,
    "start_ts" bigint not null,
    "end_ts" bigint,
    "distance_km" double precision not null,
    "item" jsonb not null,
    "fare_estimate" bigint,
    "fare_lamports" bigint not null
      );



  create table "public"."bz-----------TELEGRAM DB----------" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."bz-----------TELEGRAM DB----------" enable row level security;


  create table "public"."drivers" (
    "driver_id" uuid not null,
    "driver_pubkey" jsonb not null,
    "name" text not null,
    "email" text not null,
    "phone" text not null,
    "status" text not null,
    "driver_location" jsonb not null,
    "license_number" text,
    "vehicle_type" text not null,
    "driver_response" jsonb not null,
    "vehicle" text
      );



  create table "public"."ride_request" (
    "request_id" uuid not null,
    "rider_id" uuid not null,
    "pick_up" jsonb not null,
    "drop_off" jsonb not null,
    "estimated_price" bigint not null,
    "distance_km" double precision not null,
    "estimated_time_min" integer not null,
    "ride_type" jsonb not null,
    "items" jsonb not null,
    "payment_method" text not null,
    "order_id" uuid,
    "user_id" bigint,
    "user_phone_number" text,
    "vendor_phone_number" text
      );



  create table "public"."riders" (
    "rider_id" uuid not null,
    "rider_pubkey" jsonb not null,
    "name" text not null,
    "email" text not null,
    "phone" text not null
      );



  create table "public"."telegram_bots" (
    "id" bigint generated always as identity not null,
    "bot_id" bigint not null,
    "bot_username" text not null,
    "bot_token" text not null,
    "vendor_id" bigint not null,
    "is_active" boolean not null default true,
    "created_at" timestamp with time zone default now()
      );



  create table "public"."telegram_cart" (
    "id" bigint generated always as identity not null,
    "user_id" bigint,
    "vendor_id" bigint,
    "status" text not null default 'active'::text,
    "items" jsonb not null default '[]'::jsonb,
    "total" bigint not null default 0,
    "cart_message_id" bigint
      );



  create table "public"."telegram_custom_users" (
    "id" bigint generated always as identity not null,
    "telegram_user_id" bigint not null,
    "name" text not null default ''::text,
    "phone" text not null default ''::text,
    "default_lat" double precision,
    "default_lng" double precision,
    "status" text not null default 'active'::text,
    "created_at" timestamp with time zone default now()
      );



  create table "public"."telegram_orders" (
    "id" bigint generated always as identity not null,
    "zazu_sub_name" text,
    "user_id" bigint,
    "vendor_id" bigint,
    "status" text not null default 'pending'::text,
    "subtotal" bigint not null,
    "delivery_fee" bigint not null,
    "total" bigint not null,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );



  create table "public"."telegram_payments" (
    "id" integer generated always as identity not null,
    "order_id" integer not null,
    "zazu_sub_name" text,
    "paystack_ref" text not null,
    "amount" integer not null,
    "status" text not null default 'pending'::text
      );



  create table "public"."telegram_vendor" (
    "id" bigint generated always as identity not null,
    "name" text not null,
    "address" text not null,
    "open_time" time without time zone not null,
    "close_time" time without time zone not null,
    "lat" double precision not null,
    "lng" double precision not null,
    "allows_logistics" boolean not null default true,
    "acct_type" text not null default 'vendor'::text,
    "phone" text not null,
    "email" text not null,
    "message_body" text,
    "acct_details" jsonb,
    "order_history" jsonb not null default '[]'::jsonb,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );



  create table "public"."telegram_vendor_item" (
    "id" bigint generated always as identity not null,
    "vendor_id" bigint,
    "image_url" text,
    "name" text not null,
    "menu_id" bigint,
    "price" bigint not null,
    "stock" bigint not null default 0
      );



  create table "public"."telegram_vendor_menu" (
    "id" bigint generated always as identity not null,
    "vendor_id" bigint not null,
    "category_name" text not null default 'Uncategorized'::text
      );



  create table "public"."trips" (
    "trip_id" bytea not null,
    "rider_id" uuid not null,
    "reference" text not null,
    "pick_up" text not null,
    "drop_off" text not null,
    "driver_location" text not null,
    "rider_pubkey" text not null,
    "driver_pubkey" text not null,
    "driver_id" uuid not null,
    "status" text not null,
    "start_ts" bigint not null,
    "end_ts" bigint,
    "distance_km" double precision not null,
    "item" jsonb not null,
    "fare_estimate" bigint,
    "fare_lamports" bigint,
    "rider_email" text not null default ''::text
      );


CREATE UNIQUE INDEX __diesel_schema_migrations_pkey ON public.back__diesel_schema_migrations USING btree (version);

CREATE UNIQUE INDEX __diesel_schema_migrations_pkey1 ON public.__diesel_schema_migrations USING btree (version);

CREATE UNIQUE INDEX app_delivery_orders_waypoints_pkey ON public.app_delivery_orders_waypoints USING btree (created_at, id);

CREATE UNIQUE INDEX "azzz----------APP DB-------_pkey" ON public."azzz----------BACKEND DB-------" USING btree (id);

CREATE UNIQUE INDEX "bz------TELEGRAM DB------_pkey" ON public."bz-----------TELEGRAM DB----------" USING btree (id);

CREATE UNIQUE INDEX cus_users_pkey ON public.app_custom_users USING btree (id);

CREATE UNIQUE INDEX delivery_orders_order_code_key ON public.app_delivery_orders USING btree (order_code);

CREATE UNIQUE INDEX delivery_orders_pkey ON public.app_delivery_orders USING btree (id);

CREATE UNIQUE INDEX drivers_email_key ON public.back_drivers USING btree (email);

CREATE UNIQUE INDEX drivers_email_key1 ON public.drivers USING btree (email);

CREATE UNIQUE INDEX drivers_pkey ON public.back_drivers USING btree (driver_id);

CREATE UNIQUE INDEX drivers_pkey1 ON public.drivers USING btree (driver_id);

CREATE UNIQUE INDEX location_pkey ON public.app_locations USING btree (id);

CREATE UNIQUE INDEX messages_pkey ON public.app_messages USING btree (id);

CREATE UNIQUE INDEX package_images_pkey ON public.app_package_images USING btree (id);

CREATE UNIQUE INDEX package_images_url_key ON public.app_package_images USING btree (url);

CREATE UNIQUE INDEX ride_request_pkey ON public.back_ride_request USING btree (request_id);

CREATE UNIQUE INDEX ride_request_pkey1 ON public.ride_request USING btree (request_id);

CREATE UNIQUE INDEX riders_current_statuss_pkey ON public.app_riders_current_status USING btree (id);

CREATE UNIQUE INDEX riders_email_key ON public.back_custom_users USING btree (email);

CREATE UNIQUE INDEX riders_email_key1 ON public.riders USING btree (email);

CREATE UNIQUE INDEX riders_pkey ON public.back_custom_users USING btree (rider_id);

CREATE UNIQUE INDEX riders_pkey1 ON public.riders USING btree (rider_id);

CREATE UNIQUE INDEX saved_locations_pkey ON public.app_saved_locations USING btree (id);

CREATE UNIQUE INDEX settings_pkey ON public.app_settings USING btree (id);

CREATE UNIQUE INDEX telegram_bots_bot_id_key ON public.telegram_bots USING btree (bot_id);

CREATE UNIQUE INDEX telegram_bots_bot_token_key ON public.telegram_bots USING btree (bot_token);

CREATE UNIQUE INDEX telegram_bots_bot_username_key ON public.telegram_bots USING btree (bot_username);

CREATE UNIQUE INDEX telegram_bots_pkey ON public.telegram_bots USING btree (id);

CREATE UNIQUE INDEX telegram_cart_one_active_per_vendor ON public.telegram_cart USING btree (user_id, vendor_id) WHERE (status = 'active'::text);

CREATE UNIQUE INDEX telegram_cart_pkey ON public.telegram_cart USING btree (id);

CREATE UNIQUE INDEX telegram_custom_users_pkey ON public.telegram_custom_users USING btree (id);

CREATE UNIQUE INDEX telegram_custom_users_telegram_user_id_key ON public.telegram_custom_users USING btree (telegram_user_id);

CREATE UNIQUE INDEX telegram_orders_pkey ON public.telegram_orders USING btree (id);

CREATE UNIQUE INDEX telegram_payments_pkey ON public.telegram_payments USING btree (id);

CREATE UNIQUE INDEX telegram_vendor_item_pkey ON public.telegram_vendor_item USING btree (id);

CREATE UNIQUE INDEX telegram_vendor_menu_pkey ON public.telegram_vendor_menu USING btree (id);

CREATE UNIQUE INDEX telegram_vendor_name_key ON public.telegram_vendor USING btree (name);

CREATE UNIQUE INDEX telegram_vendor_pkey ON public.telegram_vendor USING btree (id);

CREATE UNIQUE INDEX trips_pkey ON public.back_trips USING btree (trip_id);

CREATE UNIQUE INDEX trips_pkey1 ON public.trips USING btree (trip_id);

CREATE UNIQUE INDEX unique_vendor_category ON public.telegram_vendor_menu USING btree (vendor_id, category_name);

alter table "public"."__diesel_schema_migrations" add constraint "__diesel_schema_migrations_pkey1" PRIMARY KEY using index "__diesel_schema_migrations_pkey1";

alter table "public"."app_custom_users" add constraint "cus_users_pkey" PRIMARY KEY using index "cus_users_pkey";

alter table "public"."app_delivery_orders" add constraint "delivery_orders_pkey" PRIMARY KEY using index "delivery_orders_pkey";

alter table "public"."app_delivery_orders_waypoints" add constraint "app_delivery_orders_waypoints_pkey" PRIMARY KEY using index "app_delivery_orders_waypoints_pkey";

alter table "public"."app_locations" add constraint "location_pkey" PRIMARY KEY using index "location_pkey";

alter table "public"."app_messages" add constraint "messages_pkey" PRIMARY KEY using index "messages_pkey";

alter table "public"."app_package_images" add constraint "package_images_pkey" PRIMARY KEY using index "package_images_pkey";

alter table "public"."app_riders_current_status" add constraint "riders_current_statuss_pkey" PRIMARY KEY using index "riders_current_statuss_pkey";

alter table "public"."app_saved_locations" add constraint "saved_locations_pkey" PRIMARY KEY using index "saved_locations_pkey";

alter table "public"."app_settings" add constraint "settings_pkey" PRIMARY KEY using index "settings_pkey";

alter table "public"."azzz----------BACKEND DB-------" add constraint "azzz----------APP DB-------_pkey" PRIMARY KEY using index "azzz----------APP DB-------_pkey";

alter table "public"."back__diesel_schema_migrations" add constraint "__diesel_schema_migrations_pkey" PRIMARY KEY using index "__diesel_schema_migrations_pkey";

alter table "public"."back_custom_users" add constraint "riders_pkey" PRIMARY KEY using index "riders_pkey";

alter table "public"."back_drivers" add constraint "drivers_pkey" PRIMARY KEY using index "drivers_pkey";

alter table "public"."back_ride_request" add constraint "ride_request_pkey" PRIMARY KEY using index "ride_request_pkey";

alter table "public"."back_trips" add constraint "trips_pkey" PRIMARY KEY using index "trips_pkey";

alter table "public"."bz-----------TELEGRAM DB----------" add constraint "bz------TELEGRAM DB------_pkey" PRIMARY KEY using index "bz------TELEGRAM DB------_pkey";

alter table "public"."drivers" add constraint "drivers_pkey1" PRIMARY KEY using index "drivers_pkey1";

alter table "public"."ride_request" add constraint "ride_request_pkey1" PRIMARY KEY using index "ride_request_pkey1";

alter table "public"."riders" add constraint "riders_pkey1" PRIMARY KEY using index "riders_pkey1";

alter table "public"."telegram_bots" add constraint "telegram_bots_pkey" PRIMARY KEY using index "telegram_bots_pkey";

alter table "public"."telegram_cart" add constraint "telegram_cart_pkey" PRIMARY KEY using index "telegram_cart_pkey";

alter table "public"."telegram_custom_users" add constraint "telegram_custom_users_pkey" PRIMARY KEY using index "telegram_custom_users_pkey";

alter table "public"."telegram_orders" add constraint "telegram_orders_pkey" PRIMARY KEY using index "telegram_orders_pkey";

alter table "public"."telegram_payments" add constraint "telegram_payments_pkey" PRIMARY KEY using index "telegram_payments_pkey";

alter table "public"."telegram_vendor" add constraint "telegram_vendor_pkey" PRIMARY KEY using index "telegram_vendor_pkey";

alter table "public"."telegram_vendor_item" add constraint "telegram_vendor_item_pkey" PRIMARY KEY using index "telegram_vendor_item_pkey";

alter table "public"."telegram_vendor_menu" add constraint "telegram_vendor_menu_pkey" PRIMARY KEY using index "telegram_vendor_menu_pkey";

alter table "public"."trips" add constraint "trips_pkey1" PRIMARY KEY using index "trips_pkey1";

alter table "public"."app_custom_users" add constraint "cus_users_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."app_custom_users" validate constraint "cus_users_id_fkey";

alter table "public"."app_delivery_orders" add constraint "delivery_orders_client_id_fkey" FOREIGN KEY (client_id) REFERENCES public.app_custom_users(id) not valid;

alter table "public"."app_delivery_orders" validate constraint "delivery_orders_client_id_fkey";

alter table "public"."app_delivery_orders" add constraint "delivery_orders_driver_id_fkey1" FOREIGN KEY (driver_id) REFERENCES public.app_custom_users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."app_delivery_orders" validate constraint "delivery_orders_driver_id_fkey1";

alter table "public"."app_delivery_orders" add constraint "delivery_orders_order_code_key" UNIQUE using index "delivery_orders_order_code_key";

alter table "public"."app_delivery_orders_waypoints" add constraint "delivery_orders_waypoints_order_id_fkey" FOREIGN KEY (order_id) REFERENCES public.app_delivery_orders(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."app_delivery_orders_waypoints" validate constraint "delivery_orders_waypoints_order_id_fkey";

alter table "public"."app_messages" add constraint "messages_delivery_order_id_fkey" FOREIGN KEY (delivery_order_id) REFERENCES public.app_delivery_orders(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."app_messages" validate constraint "messages_delivery_order_id_fkey";

alter table "public"."app_messages" add constraint "messages_receiver_id_fkey" FOREIGN KEY (receiver_id) REFERENCES public.app_custom_users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."app_messages" validate constraint "messages_receiver_id_fkey";

alter table "public"."app_messages" add constraint "messages_sender_id_fkey" FOREIGN KEY (sender_id) REFERENCES public.app_custom_users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."app_messages" validate constraint "messages_sender_id_fkey";

alter table "public"."app_package_images" add constraint "package_images_url_key" UNIQUE using index "package_images_url_key";

alter table "public"."app_package_images" add constraint "package_images_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."app_package_images" validate constraint "package_images_user_id_fkey";

alter table "public"."app_riders_current_status" add constraint "riders_current_statuss_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."app_riders_current_status" validate constraint "riders_current_statuss_id_fkey";

alter table "public"."app_saved_locations" add constraint "saved_locations_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."app_saved_locations" validate constraint "saved_locations_user_id_fkey";

alter table "public"."app_settings" add constraint "settings_id_fkey" FOREIGN KEY (id) REFERENCES public.app_custom_users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."app_settings" validate constraint "settings_id_fkey";

alter table "public"."back_custom_users" add constraint "back_custom_users_rider_id_fkey" FOREIGN KEY (rider_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."back_custom_users" validate constraint "back_custom_users_rider_id_fkey";

alter table "public"."back_custom_users" add constraint "riders_email_key" UNIQUE using index "riders_email_key";

alter table "public"."back_drivers" add constraint "drivers_email_key" UNIQUE using index "drivers_email_key";

alter table "public"."drivers" add constraint "drivers_email_key1" UNIQUE using index "drivers_email_key1";

alter table "public"."riders" add constraint "riders_email_key1" UNIQUE using index "riders_email_key1";

alter table "public"."telegram_bots" add constraint "telegram_bots_bot_id_key" UNIQUE using index "telegram_bots_bot_id_key";

alter table "public"."telegram_bots" add constraint "telegram_bots_bot_token_key" UNIQUE using index "telegram_bots_bot_token_key";

alter table "public"."telegram_bots" add constraint "telegram_bots_bot_username_key" UNIQUE using index "telegram_bots_bot_username_key";

alter table "public"."telegram_bots" add constraint "telegram_bots_vendor_id_fkey" FOREIGN KEY (vendor_id) REFERENCES public.telegram_vendor(id) ON DELETE CASCADE not valid;

alter table "public"."telegram_bots" validate constraint "telegram_bots_vendor_id_fkey";

alter table "public"."telegram_cart" add constraint "telegram_cart_status_check" CHECK ((status = ANY (ARRAY['active'::text, 'checked_out'::text, 'cancelled'::text]))) not valid;

alter table "public"."telegram_cart" validate constraint "telegram_cart_status_check";

alter table "public"."telegram_cart" add constraint "telegram_cart_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.telegram_custom_users(telegram_user_id) not valid;

alter table "public"."telegram_cart" validate constraint "telegram_cart_user_id_fkey";

alter table "public"."telegram_cart" add constraint "telegram_cart_vendor_id_fkey" FOREIGN KEY (vendor_id) REFERENCES public.telegram_vendor(id) not valid;

alter table "public"."telegram_cart" validate constraint "telegram_cart_vendor_id_fkey";

alter table "public"."telegram_custom_users" add constraint "telegram_custom_users_status_check" CHECK ((status = ANY (ARRAY['active'::text, 'hold'::text]))) not valid;

alter table "public"."telegram_custom_users" validate constraint "telegram_custom_users_status_check";

alter table "public"."telegram_custom_users" add constraint "telegram_custom_users_telegram_user_id_key" UNIQUE using index "telegram_custom_users_telegram_user_id_key";

alter table "public"."telegram_orders" add constraint "telegram_orders_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'paid'::text, 'in_progress'::text, 'delivered'::text, 'cancelled'::text]))) not valid;

alter table "public"."telegram_orders" validate constraint "telegram_orders_status_check";

alter table "public"."telegram_orders" add constraint "telegram_orders_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.telegram_custom_users(telegram_user_id) not valid;

alter table "public"."telegram_orders" validate constraint "telegram_orders_user_id_fkey";

alter table "public"."telegram_orders" add constraint "telegram_orders_vendor_id_fkey" FOREIGN KEY (vendor_id) REFERENCES public.telegram_vendor(id) not valid;

alter table "public"."telegram_orders" validate constraint "telegram_orders_vendor_id_fkey";

alter table "public"."telegram_orders" add constraint "telegram_orders_zazu_sub_name_fkey" FOREIGN KEY (zazu_sub_name) REFERENCES public.telegram_vendor(name) not valid;

alter table "public"."telegram_orders" validate constraint "telegram_orders_zazu_sub_name_fkey";

alter table "public"."telegram_payments" add constraint "telegram_payments_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'success'::text, 'failed'::text]))) not valid;

alter table "public"."telegram_payments" validate constraint "telegram_payments_status_check";

alter table "public"."telegram_vendor" add constraint "telegram_vendor_acct_type_check" CHECK ((acct_type = ANY (ARRAY['vendor'::text, 'Handy-man'::text, 'service-provider'::text]))) not valid;

alter table "public"."telegram_vendor" validate constraint "telegram_vendor_acct_type_check";

alter table "public"."telegram_vendor" add constraint "telegram_vendor_name_key" UNIQUE using index "telegram_vendor_name_key";

alter table "public"."telegram_vendor_item" add constraint "telegram_vendor_item_menu_id_fkey" FOREIGN KEY (menu_id) REFERENCES public.telegram_vendor_menu(id) not valid;

alter table "public"."telegram_vendor_item" validate constraint "telegram_vendor_item_menu_id_fkey";

alter table "public"."telegram_vendor_item" add constraint "telegram_vendor_item_vendor_id_fkey" FOREIGN KEY (vendor_id) REFERENCES public.telegram_vendor(id) not valid;

alter table "public"."telegram_vendor_item" validate constraint "telegram_vendor_item_vendor_id_fkey";

alter table "public"."telegram_vendor_menu" add constraint "telegram_vendor_menu_vendor_id_fkey" FOREIGN KEY (vendor_id) REFERENCES public.telegram_vendor(id) not valid;

alter table "public"."telegram_vendor_menu" validate constraint "telegram_vendor_menu_vendor_id_fkey";

alter table "public"."telegram_vendor_menu" add constraint "unique_vendor_category" UNIQUE using index "unique_vendor_category";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.append_waypoints(p_order_id bigint, p_new_waypoints jsonb, p_current_lat double precision, p_current_lng double precision)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  waypoint_count INT;
  total_waypoints INT;
  rider_uuid UUID;
BEGIN

  -- Count received waypoints
  waypoint_count := jsonb_array_length(p_new_waypoints);

  -- Insert each waypoint as a separate row
  INSERT INTO public.delivery_orders_waypoints (
    order_id,
    lat,
    long,
    created_at
  )
  SELECT
    p_order_id,
    (w->>'lat')::DOUBLE PRECISION,
    (w->>'lng')::DOUBLE PRECISION,
    COALESCE((w->>'timestamp')::timestamptz, now())
  FROM jsonb_array_elements(p_new_waypoints) w;

  -- Update current driver location in delivery_orders
    UPDATE public.riders_current_status
    SET 
      latitude = p_current_lat,
      longitude = p_current_lng,
      updated_at = now()
    WHERE id = rider_uuid;

  -- Count total waypoints for this order
  SELECT COUNT(*)
  INTO total_waypoints
  FROM public.delivery_orders_waypoints
  WHERE order_id = p_order_id;

  -- Return debug object
  RETURN jsonb_build_object(
    'success', true,
    'order_id', p_order_id,
    'driver_id', rider_uuid,
    'waypoints_received', waypoint_count,
    'total_waypoints_in_db', total_waypoints,
    'current_lat', p_current_lat,
    'current_lng', p_current_lng,
    'updated_at', now()
  );

END;
$function$
;

CREATE OR REPLACE FUNCTION public.diesel_manage_updated_at(_tbl regclass)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
    EXECUTE format('CREATE TRIGGER set_updated_at BEFORE UPDATE ON %s
                    FOR EACH ROW EXECUTE PROCEDURE diesel_set_updated_at()', _tbl);
END;
$function$
;

CREATE OR REPLACE FUNCTION public.diesel_set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    IF (
        NEW IS DISTINCT FROM OLD AND
        NEW.updated_at IS NOT DISTINCT FROM OLD.updated_at
    ) THEN
        NEW.updated_at := current_timestamp;
    END IF;
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.telegram_get_nearby_riders(user_lat double precision, user_lng double precision, radius_km double precision DEFAULT 10)
 RETURNS TABLE(id uuid, latitude numeric, longitude numeric, distance_km double precision)
 LANGUAGE sql
 STABLE
AS $function$
  SELECT id, latitude, longitude, distance_km
  FROM (
    SELECT
      r.id,
      r.latitude,
      r.longitude,
      ( 6371 * acos(
          LEAST(1.0, cos(radians(user_lat)) * cos(radians(r.latitude::DOUBLE PRECISION))
          * cos(radians(r.longitude::DOUBLE PRECISION) - radians(user_lng))
          + sin(radians(user_lat)) * sin(radians(r.latitude::DOUBLE PRECISION)))
      )) AS distance_km
    FROM public.app_riders_current_status r
    WHERE r.active_mode = 'rider'
  ) sub
  WHERE sub.distance_km <= radius_km
  ORDER BY sub.distance_km ASC;
$function$
;

grant delete on table "public"."__diesel_schema_migrations" to "anon";

grant insert on table "public"."__diesel_schema_migrations" to "anon";

grant references on table "public"."__diesel_schema_migrations" to "anon";

grant select on table "public"."__diesel_schema_migrations" to "anon";

grant trigger on table "public"."__diesel_schema_migrations" to "anon";

grant truncate on table "public"."__diesel_schema_migrations" to "anon";

grant update on table "public"."__diesel_schema_migrations" to "anon";

grant delete on table "public"."__diesel_schema_migrations" to "authenticated";

grant insert on table "public"."__diesel_schema_migrations" to "authenticated";

grant references on table "public"."__diesel_schema_migrations" to "authenticated";

grant select on table "public"."__diesel_schema_migrations" to "authenticated";

grant trigger on table "public"."__diesel_schema_migrations" to "authenticated";

grant truncate on table "public"."__diesel_schema_migrations" to "authenticated";

grant update on table "public"."__diesel_schema_migrations" to "authenticated";

grant delete on table "public"."__diesel_schema_migrations" to "service_role";

grant insert on table "public"."__diesel_schema_migrations" to "service_role";

grant references on table "public"."__diesel_schema_migrations" to "service_role";

grant select on table "public"."__diesel_schema_migrations" to "service_role";

grant trigger on table "public"."__diesel_schema_migrations" to "service_role";

grant truncate on table "public"."__diesel_schema_migrations" to "service_role";

grant update on table "public"."__diesel_schema_migrations" to "service_role";

grant delete on table "public"."app_custom_users" to "anon";

grant insert on table "public"."app_custom_users" to "anon";

grant references on table "public"."app_custom_users" to "anon";

grant select on table "public"."app_custom_users" to "anon";

grant trigger on table "public"."app_custom_users" to "anon";

grant truncate on table "public"."app_custom_users" to "anon";

grant update on table "public"."app_custom_users" to "anon";

grant delete on table "public"."app_custom_users" to "authenticated";

grant insert on table "public"."app_custom_users" to "authenticated";

grant references on table "public"."app_custom_users" to "authenticated";

grant select on table "public"."app_custom_users" to "authenticated";

grant trigger on table "public"."app_custom_users" to "authenticated";

grant truncate on table "public"."app_custom_users" to "authenticated";

grant update on table "public"."app_custom_users" to "authenticated";

grant delete on table "public"."app_custom_users" to "service_role";

grant insert on table "public"."app_custom_users" to "service_role";

grant references on table "public"."app_custom_users" to "service_role";

grant select on table "public"."app_custom_users" to "service_role";

grant trigger on table "public"."app_custom_users" to "service_role";

grant truncate on table "public"."app_custom_users" to "service_role";

grant update on table "public"."app_custom_users" to "service_role";

grant delete on table "public"."app_delivery_orders" to "anon";

grant insert on table "public"."app_delivery_orders" to "anon";

grant references on table "public"."app_delivery_orders" to "anon";

grant select on table "public"."app_delivery_orders" to "anon";

grant trigger on table "public"."app_delivery_orders" to "anon";

grant truncate on table "public"."app_delivery_orders" to "anon";

grant update on table "public"."app_delivery_orders" to "anon";

grant delete on table "public"."app_delivery_orders" to "authenticated";

grant insert on table "public"."app_delivery_orders" to "authenticated";

grant references on table "public"."app_delivery_orders" to "authenticated";

grant select on table "public"."app_delivery_orders" to "authenticated";

grant trigger on table "public"."app_delivery_orders" to "authenticated";

grant truncate on table "public"."app_delivery_orders" to "authenticated";

grant update on table "public"."app_delivery_orders" to "authenticated";

grant delete on table "public"."app_delivery_orders" to "service_role";

grant insert on table "public"."app_delivery_orders" to "service_role";

grant references on table "public"."app_delivery_orders" to "service_role";

grant select on table "public"."app_delivery_orders" to "service_role";

grant trigger on table "public"."app_delivery_orders" to "service_role";

grant truncate on table "public"."app_delivery_orders" to "service_role";

grant update on table "public"."app_delivery_orders" to "service_role";

grant delete on table "public"."app_delivery_orders_waypoints" to "anon";

grant insert on table "public"."app_delivery_orders_waypoints" to "anon";

grant references on table "public"."app_delivery_orders_waypoints" to "anon";

grant select on table "public"."app_delivery_orders_waypoints" to "anon";

grant trigger on table "public"."app_delivery_orders_waypoints" to "anon";

grant truncate on table "public"."app_delivery_orders_waypoints" to "anon";

grant update on table "public"."app_delivery_orders_waypoints" to "anon";

grant delete on table "public"."app_delivery_orders_waypoints" to "authenticated";

grant insert on table "public"."app_delivery_orders_waypoints" to "authenticated";

grant references on table "public"."app_delivery_orders_waypoints" to "authenticated";

grant select on table "public"."app_delivery_orders_waypoints" to "authenticated";

grant trigger on table "public"."app_delivery_orders_waypoints" to "authenticated";

grant truncate on table "public"."app_delivery_orders_waypoints" to "authenticated";

grant update on table "public"."app_delivery_orders_waypoints" to "authenticated";

grant delete on table "public"."app_delivery_orders_waypoints" to "service_role";

grant insert on table "public"."app_delivery_orders_waypoints" to "service_role";

grant references on table "public"."app_delivery_orders_waypoints" to "service_role";

grant select on table "public"."app_delivery_orders_waypoints" to "service_role";

grant trigger on table "public"."app_delivery_orders_waypoints" to "service_role";

grant truncate on table "public"."app_delivery_orders_waypoints" to "service_role";

grant update on table "public"."app_delivery_orders_waypoints" to "service_role";

grant delete on table "public"."app_locations" to "anon";

grant insert on table "public"."app_locations" to "anon";

grant references on table "public"."app_locations" to "anon";

grant select on table "public"."app_locations" to "anon";

grant trigger on table "public"."app_locations" to "anon";

grant truncate on table "public"."app_locations" to "anon";

grant update on table "public"."app_locations" to "anon";

grant delete on table "public"."app_locations" to "authenticated";

grant insert on table "public"."app_locations" to "authenticated";

grant references on table "public"."app_locations" to "authenticated";

grant select on table "public"."app_locations" to "authenticated";

grant trigger on table "public"."app_locations" to "authenticated";

grant truncate on table "public"."app_locations" to "authenticated";

grant update on table "public"."app_locations" to "authenticated";

grant delete on table "public"."app_locations" to "service_role";

grant insert on table "public"."app_locations" to "service_role";

grant references on table "public"."app_locations" to "service_role";

grant select on table "public"."app_locations" to "service_role";

grant trigger on table "public"."app_locations" to "service_role";

grant truncate on table "public"."app_locations" to "service_role";

grant update on table "public"."app_locations" to "service_role";

grant delete on table "public"."app_messages" to "anon";

grant insert on table "public"."app_messages" to "anon";

grant references on table "public"."app_messages" to "anon";

grant select on table "public"."app_messages" to "anon";

grant trigger on table "public"."app_messages" to "anon";

grant truncate on table "public"."app_messages" to "anon";

grant update on table "public"."app_messages" to "anon";

grant delete on table "public"."app_messages" to "authenticated";

grant insert on table "public"."app_messages" to "authenticated";

grant references on table "public"."app_messages" to "authenticated";

grant select on table "public"."app_messages" to "authenticated";

grant trigger on table "public"."app_messages" to "authenticated";

grant truncate on table "public"."app_messages" to "authenticated";

grant update on table "public"."app_messages" to "authenticated";

grant delete on table "public"."app_messages" to "service_role";

grant insert on table "public"."app_messages" to "service_role";

grant references on table "public"."app_messages" to "service_role";

grant select on table "public"."app_messages" to "service_role";

grant trigger on table "public"."app_messages" to "service_role";

grant truncate on table "public"."app_messages" to "service_role";

grant update on table "public"."app_messages" to "service_role";

grant delete on table "public"."app_package_images" to "anon";

grant insert on table "public"."app_package_images" to "anon";

grant references on table "public"."app_package_images" to "anon";

grant select on table "public"."app_package_images" to "anon";

grant trigger on table "public"."app_package_images" to "anon";

grant truncate on table "public"."app_package_images" to "anon";

grant update on table "public"."app_package_images" to "anon";

grant delete on table "public"."app_package_images" to "authenticated";

grant insert on table "public"."app_package_images" to "authenticated";

grant references on table "public"."app_package_images" to "authenticated";

grant select on table "public"."app_package_images" to "authenticated";

grant trigger on table "public"."app_package_images" to "authenticated";

grant truncate on table "public"."app_package_images" to "authenticated";

grant update on table "public"."app_package_images" to "authenticated";

grant delete on table "public"."app_package_images" to "service_role";

grant insert on table "public"."app_package_images" to "service_role";

grant references on table "public"."app_package_images" to "service_role";

grant select on table "public"."app_package_images" to "service_role";

grant trigger on table "public"."app_package_images" to "service_role";

grant truncate on table "public"."app_package_images" to "service_role";

grant update on table "public"."app_package_images" to "service_role";

grant delete on table "public"."app_riders_current_status" to "anon";

grant insert on table "public"."app_riders_current_status" to "anon";

grant references on table "public"."app_riders_current_status" to "anon";

grant select on table "public"."app_riders_current_status" to "anon";

grant trigger on table "public"."app_riders_current_status" to "anon";

grant truncate on table "public"."app_riders_current_status" to "anon";

grant update on table "public"."app_riders_current_status" to "anon";

grant delete on table "public"."app_riders_current_status" to "authenticated";

grant insert on table "public"."app_riders_current_status" to "authenticated";

grant references on table "public"."app_riders_current_status" to "authenticated";

grant select on table "public"."app_riders_current_status" to "authenticated";

grant trigger on table "public"."app_riders_current_status" to "authenticated";

grant truncate on table "public"."app_riders_current_status" to "authenticated";

grant update on table "public"."app_riders_current_status" to "authenticated";

grant delete on table "public"."app_riders_current_status" to "service_role";

grant insert on table "public"."app_riders_current_status" to "service_role";

grant references on table "public"."app_riders_current_status" to "service_role";

grant select on table "public"."app_riders_current_status" to "service_role";

grant trigger on table "public"."app_riders_current_status" to "service_role";

grant truncate on table "public"."app_riders_current_status" to "service_role";

grant update on table "public"."app_riders_current_status" to "service_role";

grant delete on table "public"."app_saved_locations" to "anon";

grant insert on table "public"."app_saved_locations" to "anon";

grant references on table "public"."app_saved_locations" to "anon";

grant select on table "public"."app_saved_locations" to "anon";

grant trigger on table "public"."app_saved_locations" to "anon";

grant truncate on table "public"."app_saved_locations" to "anon";

grant update on table "public"."app_saved_locations" to "anon";

grant delete on table "public"."app_saved_locations" to "authenticated";

grant insert on table "public"."app_saved_locations" to "authenticated";

grant references on table "public"."app_saved_locations" to "authenticated";

grant select on table "public"."app_saved_locations" to "authenticated";

grant trigger on table "public"."app_saved_locations" to "authenticated";

grant truncate on table "public"."app_saved_locations" to "authenticated";

grant update on table "public"."app_saved_locations" to "authenticated";

grant delete on table "public"."app_saved_locations" to "service_role";

grant insert on table "public"."app_saved_locations" to "service_role";

grant references on table "public"."app_saved_locations" to "service_role";

grant select on table "public"."app_saved_locations" to "service_role";

grant trigger on table "public"."app_saved_locations" to "service_role";

grant truncate on table "public"."app_saved_locations" to "service_role";

grant update on table "public"."app_saved_locations" to "service_role";

grant delete on table "public"."app_settings" to "anon";

grant insert on table "public"."app_settings" to "anon";

grant references on table "public"."app_settings" to "anon";

grant select on table "public"."app_settings" to "anon";

grant trigger on table "public"."app_settings" to "anon";

grant truncate on table "public"."app_settings" to "anon";

grant update on table "public"."app_settings" to "anon";

grant delete on table "public"."app_settings" to "authenticated";

grant insert on table "public"."app_settings" to "authenticated";

grant references on table "public"."app_settings" to "authenticated";

grant select on table "public"."app_settings" to "authenticated";

grant trigger on table "public"."app_settings" to "authenticated";

grant truncate on table "public"."app_settings" to "authenticated";

grant update on table "public"."app_settings" to "authenticated";

grant delete on table "public"."app_settings" to "service_role";

grant insert on table "public"."app_settings" to "service_role";

grant references on table "public"."app_settings" to "service_role";

grant select on table "public"."app_settings" to "service_role";

grant trigger on table "public"."app_settings" to "service_role";

grant truncate on table "public"."app_settings" to "service_role";

grant update on table "public"."app_settings" to "service_role";

grant delete on table "public"."azzz----------BACKEND DB-------" to "anon";

grant insert on table "public"."azzz----------BACKEND DB-------" to "anon";

grant references on table "public"."azzz----------BACKEND DB-------" to "anon";

grant select on table "public"."azzz----------BACKEND DB-------" to "anon";

grant trigger on table "public"."azzz----------BACKEND DB-------" to "anon";

grant truncate on table "public"."azzz----------BACKEND DB-------" to "anon";

grant update on table "public"."azzz----------BACKEND DB-------" to "anon";

grant delete on table "public"."azzz----------BACKEND DB-------" to "authenticated";

grant insert on table "public"."azzz----------BACKEND DB-------" to "authenticated";

grant references on table "public"."azzz----------BACKEND DB-------" to "authenticated";

grant select on table "public"."azzz----------BACKEND DB-------" to "authenticated";

grant trigger on table "public"."azzz----------BACKEND DB-------" to "authenticated";

grant truncate on table "public"."azzz----------BACKEND DB-------" to "authenticated";

grant update on table "public"."azzz----------BACKEND DB-------" to "authenticated";

grant delete on table "public"."azzz----------BACKEND DB-------" to "service_role";

grant insert on table "public"."azzz----------BACKEND DB-------" to "service_role";

grant references on table "public"."azzz----------BACKEND DB-------" to "service_role";

grant select on table "public"."azzz----------BACKEND DB-------" to "service_role";

grant trigger on table "public"."azzz----------BACKEND DB-------" to "service_role";

grant truncate on table "public"."azzz----------BACKEND DB-------" to "service_role";

grant update on table "public"."azzz----------BACKEND DB-------" to "service_role";

grant delete on table "public"."back__diesel_schema_migrations" to "anon";

grant insert on table "public"."back__diesel_schema_migrations" to "anon";

grant references on table "public"."back__diesel_schema_migrations" to "anon";

grant select on table "public"."back__diesel_schema_migrations" to "anon";

grant trigger on table "public"."back__diesel_schema_migrations" to "anon";

grant truncate on table "public"."back__diesel_schema_migrations" to "anon";

grant update on table "public"."back__diesel_schema_migrations" to "anon";

grant delete on table "public"."back__diesel_schema_migrations" to "authenticated";

grant insert on table "public"."back__diesel_schema_migrations" to "authenticated";

grant references on table "public"."back__diesel_schema_migrations" to "authenticated";

grant select on table "public"."back__diesel_schema_migrations" to "authenticated";

grant trigger on table "public"."back__diesel_schema_migrations" to "authenticated";

grant truncate on table "public"."back__diesel_schema_migrations" to "authenticated";

grant update on table "public"."back__diesel_schema_migrations" to "authenticated";

grant delete on table "public"."back__diesel_schema_migrations" to "service_role";

grant insert on table "public"."back__diesel_schema_migrations" to "service_role";

grant references on table "public"."back__diesel_schema_migrations" to "service_role";

grant select on table "public"."back__diesel_schema_migrations" to "service_role";

grant trigger on table "public"."back__diesel_schema_migrations" to "service_role";

grant truncate on table "public"."back__diesel_schema_migrations" to "service_role";

grant update on table "public"."back__diesel_schema_migrations" to "service_role";

grant delete on table "public"."back_custom_users" to "anon";

grant insert on table "public"."back_custom_users" to "anon";

grant references on table "public"."back_custom_users" to "anon";

grant select on table "public"."back_custom_users" to "anon";

grant trigger on table "public"."back_custom_users" to "anon";

grant truncate on table "public"."back_custom_users" to "anon";

grant update on table "public"."back_custom_users" to "anon";

grant delete on table "public"."back_custom_users" to "authenticated";

grant insert on table "public"."back_custom_users" to "authenticated";

grant references on table "public"."back_custom_users" to "authenticated";

grant select on table "public"."back_custom_users" to "authenticated";

grant trigger on table "public"."back_custom_users" to "authenticated";

grant truncate on table "public"."back_custom_users" to "authenticated";

grant update on table "public"."back_custom_users" to "authenticated";

grant delete on table "public"."back_custom_users" to "service_role";

grant insert on table "public"."back_custom_users" to "service_role";

grant references on table "public"."back_custom_users" to "service_role";

grant select on table "public"."back_custom_users" to "service_role";

grant trigger on table "public"."back_custom_users" to "service_role";

grant truncate on table "public"."back_custom_users" to "service_role";

grant update on table "public"."back_custom_users" to "service_role";

grant delete on table "public"."back_drivers" to "anon";

grant insert on table "public"."back_drivers" to "anon";

grant references on table "public"."back_drivers" to "anon";

grant select on table "public"."back_drivers" to "anon";

grant trigger on table "public"."back_drivers" to "anon";

grant truncate on table "public"."back_drivers" to "anon";

grant update on table "public"."back_drivers" to "anon";

grant delete on table "public"."back_drivers" to "authenticated";

grant insert on table "public"."back_drivers" to "authenticated";

grant references on table "public"."back_drivers" to "authenticated";

grant select on table "public"."back_drivers" to "authenticated";

grant trigger on table "public"."back_drivers" to "authenticated";

grant truncate on table "public"."back_drivers" to "authenticated";

grant update on table "public"."back_drivers" to "authenticated";

grant delete on table "public"."back_drivers" to "service_role";

grant insert on table "public"."back_drivers" to "service_role";

grant references on table "public"."back_drivers" to "service_role";

grant select on table "public"."back_drivers" to "service_role";

grant trigger on table "public"."back_drivers" to "service_role";

grant truncate on table "public"."back_drivers" to "service_role";

grant update on table "public"."back_drivers" to "service_role";

grant delete on table "public"."back_ride_request" to "anon";

grant insert on table "public"."back_ride_request" to "anon";

grant references on table "public"."back_ride_request" to "anon";

grant select on table "public"."back_ride_request" to "anon";

grant trigger on table "public"."back_ride_request" to "anon";

grant truncate on table "public"."back_ride_request" to "anon";

grant update on table "public"."back_ride_request" to "anon";

grant delete on table "public"."back_ride_request" to "authenticated";

grant insert on table "public"."back_ride_request" to "authenticated";

grant references on table "public"."back_ride_request" to "authenticated";

grant select on table "public"."back_ride_request" to "authenticated";

grant trigger on table "public"."back_ride_request" to "authenticated";

grant truncate on table "public"."back_ride_request" to "authenticated";

grant update on table "public"."back_ride_request" to "authenticated";

grant delete on table "public"."back_ride_request" to "service_role";

grant insert on table "public"."back_ride_request" to "service_role";

grant references on table "public"."back_ride_request" to "service_role";

grant select on table "public"."back_ride_request" to "service_role";

grant trigger on table "public"."back_ride_request" to "service_role";

grant truncate on table "public"."back_ride_request" to "service_role";

grant update on table "public"."back_ride_request" to "service_role";

grant delete on table "public"."back_trips" to "anon";

grant insert on table "public"."back_trips" to "anon";

grant references on table "public"."back_trips" to "anon";

grant select on table "public"."back_trips" to "anon";

grant trigger on table "public"."back_trips" to "anon";

grant truncate on table "public"."back_trips" to "anon";

grant update on table "public"."back_trips" to "anon";

grant delete on table "public"."back_trips" to "authenticated";

grant insert on table "public"."back_trips" to "authenticated";

grant references on table "public"."back_trips" to "authenticated";

grant select on table "public"."back_trips" to "authenticated";

grant trigger on table "public"."back_trips" to "authenticated";

grant truncate on table "public"."back_trips" to "authenticated";

grant update on table "public"."back_trips" to "authenticated";

grant delete on table "public"."back_trips" to "service_role";

grant insert on table "public"."back_trips" to "service_role";

grant references on table "public"."back_trips" to "service_role";

grant select on table "public"."back_trips" to "service_role";

grant trigger on table "public"."back_trips" to "service_role";

grant truncate on table "public"."back_trips" to "service_role";

grant update on table "public"."back_trips" to "service_role";

grant delete on table "public"."bz-----------TELEGRAM DB----------" to "anon";

grant insert on table "public"."bz-----------TELEGRAM DB----------" to "anon";

grant references on table "public"."bz-----------TELEGRAM DB----------" to "anon";

grant select on table "public"."bz-----------TELEGRAM DB----------" to "anon";

grant trigger on table "public"."bz-----------TELEGRAM DB----------" to "anon";

grant truncate on table "public"."bz-----------TELEGRAM DB----------" to "anon";

grant update on table "public"."bz-----------TELEGRAM DB----------" to "anon";

grant delete on table "public"."bz-----------TELEGRAM DB----------" to "authenticated";

grant insert on table "public"."bz-----------TELEGRAM DB----------" to "authenticated";

grant references on table "public"."bz-----------TELEGRAM DB----------" to "authenticated";

grant select on table "public"."bz-----------TELEGRAM DB----------" to "authenticated";

grant trigger on table "public"."bz-----------TELEGRAM DB----------" to "authenticated";

grant truncate on table "public"."bz-----------TELEGRAM DB----------" to "authenticated";

grant update on table "public"."bz-----------TELEGRAM DB----------" to "authenticated";

grant delete on table "public"."bz-----------TELEGRAM DB----------" to "service_role";

grant insert on table "public"."bz-----------TELEGRAM DB----------" to "service_role";

grant references on table "public"."bz-----------TELEGRAM DB----------" to "service_role";

grant select on table "public"."bz-----------TELEGRAM DB----------" to "service_role";

grant trigger on table "public"."bz-----------TELEGRAM DB----------" to "service_role";

grant truncate on table "public"."bz-----------TELEGRAM DB----------" to "service_role";

grant update on table "public"."bz-----------TELEGRAM DB----------" to "service_role";

grant delete on table "public"."drivers" to "anon";

grant insert on table "public"."drivers" to "anon";

grant references on table "public"."drivers" to "anon";

grant select on table "public"."drivers" to "anon";

grant trigger on table "public"."drivers" to "anon";

grant truncate on table "public"."drivers" to "anon";

grant update on table "public"."drivers" to "anon";

grant delete on table "public"."drivers" to "authenticated";

grant insert on table "public"."drivers" to "authenticated";

grant references on table "public"."drivers" to "authenticated";

grant select on table "public"."drivers" to "authenticated";

grant trigger on table "public"."drivers" to "authenticated";

grant truncate on table "public"."drivers" to "authenticated";

grant update on table "public"."drivers" to "authenticated";

grant delete on table "public"."drivers" to "service_role";

grant insert on table "public"."drivers" to "service_role";

grant references on table "public"."drivers" to "service_role";

grant select on table "public"."drivers" to "service_role";

grant trigger on table "public"."drivers" to "service_role";

grant truncate on table "public"."drivers" to "service_role";

grant update on table "public"."drivers" to "service_role";

grant delete on table "public"."ride_request" to "anon";

grant insert on table "public"."ride_request" to "anon";

grant references on table "public"."ride_request" to "anon";

grant select on table "public"."ride_request" to "anon";

grant trigger on table "public"."ride_request" to "anon";

grant truncate on table "public"."ride_request" to "anon";

grant update on table "public"."ride_request" to "anon";

grant delete on table "public"."ride_request" to "authenticated";

grant insert on table "public"."ride_request" to "authenticated";

grant references on table "public"."ride_request" to "authenticated";

grant select on table "public"."ride_request" to "authenticated";

grant trigger on table "public"."ride_request" to "authenticated";

grant truncate on table "public"."ride_request" to "authenticated";

grant update on table "public"."ride_request" to "authenticated";

grant delete on table "public"."ride_request" to "service_role";

grant insert on table "public"."ride_request" to "service_role";

grant references on table "public"."ride_request" to "service_role";

grant select on table "public"."ride_request" to "service_role";

grant trigger on table "public"."ride_request" to "service_role";

grant truncate on table "public"."ride_request" to "service_role";

grant update on table "public"."ride_request" to "service_role";

grant delete on table "public"."riders" to "anon";

grant insert on table "public"."riders" to "anon";

grant references on table "public"."riders" to "anon";

grant select on table "public"."riders" to "anon";

grant trigger on table "public"."riders" to "anon";

grant truncate on table "public"."riders" to "anon";

grant update on table "public"."riders" to "anon";

grant delete on table "public"."riders" to "authenticated";

grant insert on table "public"."riders" to "authenticated";

grant references on table "public"."riders" to "authenticated";

grant select on table "public"."riders" to "authenticated";

grant trigger on table "public"."riders" to "authenticated";

grant truncate on table "public"."riders" to "authenticated";

grant update on table "public"."riders" to "authenticated";

grant delete on table "public"."riders" to "service_role";

grant insert on table "public"."riders" to "service_role";

grant references on table "public"."riders" to "service_role";

grant select on table "public"."riders" to "service_role";

grant trigger on table "public"."riders" to "service_role";

grant truncate on table "public"."riders" to "service_role";

grant update on table "public"."riders" to "service_role";

grant delete on table "public"."telegram_bots" to "anon";

grant insert on table "public"."telegram_bots" to "anon";

grant references on table "public"."telegram_bots" to "anon";

grant select on table "public"."telegram_bots" to "anon";

grant trigger on table "public"."telegram_bots" to "anon";

grant truncate on table "public"."telegram_bots" to "anon";

grant update on table "public"."telegram_bots" to "anon";

grant delete on table "public"."telegram_bots" to "authenticated";

grant insert on table "public"."telegram_bots" to "authenticated";

grant references on table "public"."telegram_bots" to "authenticated";

grant select on table "public"."telegram_bots" to "authenticated";

grant trigger on table "public"."telegram_bots" to "authenticated";

grant truncate on table "public"."telegram_bots" to "authenticated";

grant update on table "public"."telegram_bots" to "authenticated";

grant delete on table "public"."telegram_bots" to "service_role";

grant insert on table "public"."telegram_bots" to "service_role";

grant references on table "public"."telegram_bots" to "service_role";

grant select on table "public"."telegram_bots" to "service_role";

grant trigger on table "public"."telegram_bots" to "service_role";

grant truncate on table "public"."telegram_bots" to "service_role";

grant update on table "public"."telegram_bots" to "service_role";

grant delete on table "public"."telegram_cart" to "anon";

grant insert on table "public"."telegram_cart" to "anon";

grant references on table "public"."telegram_cart" to "anon";

grant select on table "public"."telegram_cart" to "anon";

grant trigger on table "public"."telegram_cart" to "anon";

grant truncate on table "public"."telegram_cart" to "anon";

grant update on table "public"."telegram_cart" to "anon";

grant delete on table "public"."telegram_cart" to "authenticated";

grant insert on table "public"."telegram_cart" to "authenticated";

grant references on table "public"."telegram_cart" to "authenticated";

grant select on table "public"."telegram_cart" to "authenticated";

grant trigger on table "public"."telegram_cart" to "authenticated";

grant truncate on table "public"."telegram_cart" to "authenticated";

grant update on table "public"."telegram_cart" to "authenticated";

grant delete on table "public"."telegram_cart" to "service_role";

grant insert on table "public"."telegram_cart" to "service_role";

grant references on table "public"."telegram_cart" to "service_role";

grant select on table "public"."telegram_cart" to "service_role";

grant trigger on table "public"."telegram_cart" to "service_role";

grant truncate on table "public"."telegram_cart" to "service_role";

grant update on table "public"."telegram_cart" to "service_role";

grant delete on table "public"."telegram_custom_users" to "anon";

grant insert on table "public"."telegram_custom_users" to "anon";

grant references on table "public"."telegram_custom_users" to "anon";

grant select on table "public"."telegram_custom_users" to "anon";

grant trigger on table "public"."telegram_custom_users" to "anon";

grant truncate on table "public"."telegram_custom_users" to "anon";

grant update on table "public"."telegram_custom_users" to "anon";

grant delete on table "public"."telegram_custom_users" to "authenticated";

grant insert on table "public"."telegram_custom_users" to "authenticated";

grant references on table "public"."telegram_custom_users" to "authenticated";

grant select on table "public"."telegram_custom_users" to "authenticated";

grant trigger on table "public"."telegram_custom_users" to "authenticated";

grant truncate on table "public"."telegram_custom_users" to "authenticated";

grant update on table "public"."telegram_custom_users" to "authenticated";

grant delete on table "public"."telegram_custom_users" to "service_role";

grant insert on table "public"."telegram_custom_users" to "service_role";

grant references on table "public"."telegram_custom_users" to "service_role";

grant select on table "public"."telegram_custom_users" to "service_role";

grant trigger on table "public"."telegram_custom_users" to "service_role";

grant truncate on table "public"."telegram_custom_users" to "service_role";

grant update on table "public"."telegram_custom_users" to "service_role";

grant delete on table "public"."telegram_orders" to "anon";

grant insert on table "public"."telegram_orders" to "anon";

grant references on table "public"."telegram_orders" to "anon";

grant select on table "public"."telegram_orders" to "anon";

grant trigger on table "public"."telegram_orders" to "anon";

grant truncate on table "public"."telegram_orders" to "anon";

grant update on table "public"."telegram_orders" to "anon";

grant delete on table "public"."telegram_orders" to "authenticated";

grant insert on table "public"."telegram_orders" to "authenticated";

grant references on table "public"."telegram_orders" to "authenticated";

grant select on table "public"."telegram_orders" to "authenticated";

grant trigger on table "public"."telegram_orders" to "authenticated";

grant truncate on table "public"."telegram_orders" to "authenticated";

grant update on table "public"."telegram_orders" to "authenticated";

grant delete on table "public"."telegram_orders" to "service_role";

grant insert on table "public"."telegram_orders" to "service_role";

grant references on table "public"."telegram_orders" to "service_role";

grant select on table "public"."telegram_orders" to "service_role";

grant trigger on table "public"."telegram_orders" to "service_role";

grant truncate on table "public"."telegram_orders" to "service_role";

grant update on table "public"."telegram_orders" to "service_role";

grant delete on table "public"."telegram_payments" to "anon";

grant insert on table "public"."telegram_payments" to "anon";

grant references on table "public"."telegram_payments" to "anon";

grant select on table "public"."telegram_payments" to "anon";

grant trigger on table "public"."telegram_payments" to "anon";

grant truncate on table "public"."telegram_payments" to "anon";

grant update on table "public"."telegram_payments" to "anon";

grant delete on table "public"."telegram_payments" to "authenticated";

grant insert on table "public"."telegram_payments" to "authenticated";

grant references on table "public"."telegram_payments" to "authenticated";

grant select on table "public"."telegram_payments" to "authenticated";

grant trigger on table "public"."telegram_payments" to "authenticated";

grant truncate on table "public"."telegram_payments" to "authenticated";

grant update on table "public"."telegram_payments" to "authenticated";

grant delete on table "public"."telegram_payments" to "service_role";

grant insert on table "public"."telegram_payments" to "service_role";

grant references on table "public"."telegram_payments" to "service_role";

grant select on table "public"."telegram_payments" to "service_role";

grant trigger on table "public"."telegram_payments" to "service_role";

grant truncate on table "public"."telegram_payments" to "service_role";

grant update on table "public"."telegram_payments" to "service_role";

grant delete on table "public"."telegram_vendor" to "anon";

grant insert on table "public"."telegram_vendor" to "anon";

grant references on table "public"."telegram_vendor" to "anon";

grant select on table "public"."telegram_vendor" to "anon";

grant trigger on table "public"."telegram_vendor" to "anon";

grant truncate on table "public"."telegram_vendor" to "anon";

grant update on table "public"."telegram_vendor" to "anon";

grant delete on table "public"."telegram_vendor" to "authenticated";

grant insert on table "public"."telegram_vendor" to "authenticated";

grant references on table "public"."telegram_vendor" to "authenticated";

grant select on table "public"."telegram_vendor" to "authenticated";

grant trigger on table "public"."telegram_vendor" to "authenticated";

grant truncate on table "public"."telegram_vendor" to "authenticated";

grant update on table "public"."telegram_vendor" to "authenticated";

grant delete on table "public"."telegram_vendor" to "service_role";

grant insert on table "public"."telegram_vendor" to "service_role";

grant references on table "public"."telegram_vendor" to "service_role";

grant select on table "public"."telegram_vendor" to "service_role";

grant trigger on table "public"."telegram_vendor" to "service_role";

grant truncate on table "public"."telegram_vendor" to "service_role";

grant update on table "public"."telegram_vendor" to "service_role";

grant delete on table "public"."telegram_vendor_item" to "anon";

grant insert on table "public"."telegram_vendor_item" to "anon";

grant references on table "public"."telegram_vendor_item" to "anon";

grant select on table "public"."telegram_vendor_item" to "anon";

grant trigger on table "public"."telegram_vendor_item" to "anon";

grant truncate on table "public"."telegram_vendor_item" to "anon";

grant update on table "public"."telegram_vendor_item" to "anon";

grant delete on table "public"."telegram_vendor_item" to "authenticated";

grant insert on table "public"."telegram_vendor_item" to "authenticated";

grant references on table "public"."telegram_vendor_item" to "authenticated";

grant select on table "public"."telegram_vendor_item" to "authenticated";

grant trigger on table "public"."telegram_vendor_item" to "authenticated";

grant truncate on table "public"."telegram_vendor_item" to "authenticated";

grant update on table "public"."telegram_vendor_item" to "authenticated";

grant delete on table "public"."telegram_vendor_item" to "service_role";

grant insert on table "public"."telegram_vendor_item" to "service_role";

grant references on table "public"."telegram_vendor_item" to "service_role";

grant select on table "public"."telegram_vendor_item" to "service_role";

grant trigger on table "public"."telegram_vendor_item" to "service_role";

grant truncate on table "public"."telegram_vendor_item" to "service_role";

grant update on table "public"."telegram_vendor_item" to "service_role";

grant delete on table "public"."telegram_vendor_menu" to "anon";

grant insert on table "public"."telegram_vendor_menu" to "anon";

grant references on table "public"."telegram_vendor_menu" to "anon";

grant select on table "public"."telegram_vendor_menu" to "anon";

grant trigger on table "public"."telegram_vendor_menu" to "anon";

grant truncate on table "public"."telegram_vendor_menu" to "anon";

grant update on table "public"."telegram_vendor_menu" to "anon";

grant delete on table "public"."telegram_vendor_menu" to "authenticated";

grant insert on table "public"."telegram_vendor_menu" to "authenticated";

grant references on table "public"."telegram_vendor_menu" to "authenticated";

grant select on table "public"."telegram_vendor_menu" to "authenticated";

grant trigger on table "public"."telegram_vendor_menu" to "authenticated";

grant truncate on table "public"."telegram_vendor_menu" to "authenticated";

grant update on table "public"."telegram_vendor_menu" to "authenticated";

grant delete on table "public"."telegram_vendor_menu" to "service_role";

grant insert on table "public"."telegram_vendor_menu" to "service_role";

grant references on table "public"."telegram_vendor_menu" to "service_role";

grant select on table "public"."telegram_vendor_menu" to "service_role";

grant trigger on table "public"."telegram_vendor_menu" to "service_role";

grant truncate on table "public"."telegram_vendor_menu" to "service_role";

grant update on table "public"."telegram_vendor_menu" to "service_role";

grant delete on table "public"."trips" to "anon";

grant insert on table "public"."trips" to "anon";

grant references on table "public"."trips" to "anon";

grant select on table "public"."trips" to "anon";

grant trigger on table "public"."trips" to "anon";

grant truncate on table "public"."trips" to "anon";

grant update on table "public"."trips" to "anon";

grant delete on table "public"."trips" to "authenticated";

grant insert on table "public"."trips" to "authenticated";

grant references on table "public"."trips" to "authenticated";

grant select on table "public"."trips" to "authenticated";

grant trigger on table "public"."trips" to "authenticated";

grant truncate on table "public"."trips" to "authenticated";

grant update on table "public"."trips" to "authenticated";

grant delete on table "public"."trips" to "service_role";

grant insert on table "public"."trips" to "service_role";

grant references on table "public"."trips" to "service_role";

grant select on table "public"."trips" to "service_role";

grant trigger on table "public"."trips" to "service_role";

grant truncate on table "public"."trips" to "service_role";

grant update on table "public"."trips" to "service_role";


  create policy "custom_table_policy"
  on "public"."app_custom_users"
  as permissive
  for all
  to public
using (true)
with check (true);



  create policy "delivery_orders"
  on "public"."app_delivery_orders"
  as permissive
  for all
  to public
using (true);



  create policy "delivery_orders_waypoints"
  on "public"."app_delivery_orders_waypoints"
  as permissive
  for all
  to public
using (true);



  create policy "Message Policy"
  on "public"."app_messages"
  as permissive
  for all
  to public
using (true);



  create policy "Policy with security definer functions"
  on "public"."app_package_images"
  as permissive
  for all
  to anon, authenticated
using (true);



  create policy "Riders Status"
  on "public"."app_riders_current_status"
  as permissive
  for all
  to public
using (true);



  create policy "save location"
  on "public"."app_saved_locations"
  as permissive
  for all
  to public
using (true);



  create policy "settings policy"
  on "public"."app_settings"
  as permissive
  for all
  to public
using (true);



  create policy "Enable read access for all users"
  on "storage"."buckets"
  as permissive
  for all
  to public
using (true)
with check (true);



  create policy "allow all read/write 1votkep_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using (true);



  create policy "allow all read/write 1votkep_1"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check (true);



  create policy "allow all read/write 1votkep_2"
  on "storage"."objects"
  as permissive
  for update
  to public
using (true);



  create policy "allow all read/write 1votkep_3"
  on "storage"."objects"
  as permissive
  for delete
  to public
using (true);



  create policy "allow all read/write2 1votkep_0"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'package_images'::text));



  create policy "allow all read/write2 1votkep_1"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check ((bucket_id = 'package_images'::text));



  create policy "allow all read/write2 1votkep_2"
  on "storage"."objects"
  as permissive
  for update
  to public
using ((bucket_id = 'package_images'::text));



  create policy "allow all read/write2 1votkep_3"
  on "storage"."objects"
  as permissive
  for delete
  to public
using ((bucket_id = 'package_images'::text));



